
BOARD_ROWS = 25
BOARD_COLS = 50
CELL_SIZE = 20  # pixels per cell
WINDOW_WIDTH = BOARD_COLS * CELL_SIZE
WINDOW_HEIGHT = BOARD_ROWS * CELL_SIZE

SOLDIER_ROWS = 4
SOLDIER_COLS = 2
SOLDIER_BODY_ROWS = 3  # the upper part
SOLDIER_FEET_ROWS = 1  # the lower part
SOLDIER_SIZE = SOLDIER_COLS * CELL_SIZE, SOLDIER_ROWS * CELL_SIZE
SOLDIER_IMG = "soldier.png"

FLAG_ROWS = 3
FLAG_COLS = 4
FLAG_IMG = "flag.png"
FLAG_SIZE = (80, 60)

MINES_COUNT = 20
MINE_ROWS = 1
MINE_COLS = 3

BACKGROUND_COLOR = (76, 175, 80)
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)

RUNNING_STATE = 1
GRASS_IMG = "grass.png"
GRASS_SIZE = (80, 60)

WELCOME_MESSAGE = "Welcome to The Flag game. \nHave Fun!"
WELCOME_FONT_SIZE = int(0.01*WINDOW_WIDTH)
WELCOME_COLOR = WHITE
WELCOME_LOCATION = (5*20 , 5*20)
FONT_NAME = "Calibri"
